server.port=9050
spring.application.name=columnar-database-service

# Cassandra (na docker mreži)
spring.cassandra.contact-points=cassandra
spring.cassandra.port=9042
spring.cassandra.keyspace-name=nais
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS

# Eureka (ako ne vrtiš eureka-server, možeš privremeno isključiti klienta)
eureka.client.enabled=false
# eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
# eureka.client.healthcheck.enabled=true
# eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
