server.port=9050
spring.application.name=columnar-database-service

# Cassandra (приступ локалној преко cassandradb мапирања)
spring.data.cassandra.contact-points=cassandradb
spring.data.cassandra.port=9042
spring.data.cassandra.keyspace-name=nais
spring.data.cassandra.local-datacenter=datacenter1
spring.data.cassandra.schema-action=CREATE_IF_NOT_EXISTS

# Eureka (ako ne vrtiš eureka-server, možeš privremeno isključiti klienta)
eureka.client.enabled=false
# eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
# eureka.client.healthcheck.enabled=true
# eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Elasticsearch Integration (will be overridden by environment variable)
elasticsearch.service.url=http://elastic-search-service:9080

# Redis Auto-Configuration Exclusion (not used in Docker)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
