server.port=9050
spring.application.name=columnar-database-service

# Cassandra preko docker network-a (service name)
spring.data.cassandra.contact-points=cassandra
spring.data.cassandra.port=9042
spring.data.cassandra.keyspace-name=nais
spring.data.cassandra.local-datacenter=datacenter1
spring.data.cassandra.schema-action=CREATE_IF_NOT_EXISTS

# Eureka na docker mreži (ime servisa)
eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
eureka.client.healthcheck.enabled=true
eureka.instance.prefer-ip-address=true

# Dev: init šeme (ako želiš da se učita na startu i u kontejneru)
app.schema.init=true

# Actuator za health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
