server:
  port: 8083

spring:
  application:
    name: GraphDatabaseService
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true




