server:
  port: 9080

spring:
  application:
    name: elasticsearch-database-service
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://elasticsearch:9200

# Logging configuration
logging:
  level:
    rs.ac.uns.acs.nais.ElasticSearchDatabaseService: INFO
    org.springframework.data.elasticsearch: INFO

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
