version: "3.9"

services:
  cassandra:
    image: cassandra:4.1
    container_name: cta-cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=nais
      - CASSANDRA_DC=datacenter1
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SHOW VERSION"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      default:
        aliases:
          - cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: cta-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      default:
        aliases:
          - redis
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: columnar-db-service
    depends_on:
      cassandra:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Ako NE startuješ Eureku u ovom compose-u, isključi klijenta da ne spama log:
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
    ports:
      - "9050:9050"
    restart: unless-stopped

volumes:
  cassandra-data:
